# Generated by Django 3.2.2 on 2021-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard', '0003_alter_games_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='nickname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='nickname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
